### ISSUE TITLE
Code blocks always have scrollbars

### ISSUE THREAD

**Issue by tanghus** [fruux/sabre.io#11]
The css for the `<code>` tag is:

``` css
code {
    line-height: 18px;
    overflow-y: scroll;
}
```

Setting it to auto will be pwettier ;)

``` css
code {
    line-height: 18px;
    overflow-y: auto;
}
```
